import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { ethers } from 'ethers'
import { useState } from 'react'



export default function Home () {
  const [errorMessage, setErrorMessage] = useState(null)
  const [defaultAccount, setDefaultAccount] = useState(null)
  const [connButtonText, setConnButtonText] = useState('Connect Wallet')

  const [currentContractVal, setCurrentContractVal] = useState(null)

  const [provider, setProvider] = useState(null)
  const [signer, setSigner] = useState(null)
  const [contract, setContract] = useState(null)


  async function connectWalletHandler () {
    if (window.ethereum && window.ethereum.isMetaMask) {
      try {
        const result = await window.ethereum.request({ method: 'eth_requestAccounts' })
        setDefaultAccount(result[0])
        setConnButtonText('Wallet Connected')
      }

      catch (error) {
        setErrorMessage(error.message)
      }
    }

    else {
      console.log('Need to install MetaMask')
      setErrorMessage('Please install MetaMask browser extension to interact')
    }
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app'/>
        <meta name='viewport' content='width=device-width, initial-scale=1'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      <main className={styles.main}>
        <h1>HELLO</h1>

        <button onClick={connectWalletHandler}>CONNECT</button>
      </main>
    </>
  )
}
